version: '3'

services:

    kanboard:
        image: kanboard/kanboard:v1.0.45
        ports:
            - "$NETWORK_KANBOARD_GATEWAY:$PORT_00080_KANBOARD"
        volumes:
            - "$VOLUME_KANBOARD_CONFIG"

    maven:
        image: openjdk:8-jdk
        command: bash -c 'touch /test && tail -f /test'
        working_dir: /project
        volumes:
            - "$VOLUME_MAVEN_M2"
            - "$VOLUME_MAVEN_PROJECT"

networks:
    default:
        driver: bridge
        driver_opts:
            com.docker.network.enable_ipv6: "false"
            com.docker.network.bridge.name: "$NETWORK_KANBOARD_BRIDGE"
        ipam:
            driver: default
            config:
                - subnet: "$NETWORK_KANBOARD_SUBNET"
